tower/tEvents/urls.py
from django.urls import path
from . import views

app_name = 'tEvents'

urlpatterns = [
    path('', views.tEventsList, name="list"),
    path('<str:type>', views.tEventsList, name="list"),
    path('tEvents/<int:id>', views.tEventDetails, name="tEventDetails"),
    path('tEvents/<int:id>/cancel', views.cancelEvent, name="cancel"),
    path('tEvents/<int:id>/attend', views.attendEvent, name="attend"),
    path('tEvents/<int:id>/attend/premium', views.premiumEvent, name="premium"),
    path('tEvents/<int:id>/comment', views.createComment, name="comment"),
    path('tEvents/<int:id>/comment/<int:cId>', views.deleteComment, name="deleteComment"),
    path('new-tEvent/', views.createEvent, name="newEvent")
]

tower/tower/urls.py
from django.contrib import admin
from django.urls import path, include
from tEvents import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tEvents.urls'))
]

tower/tEvents/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TEvent(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    coverImg = models.CharField(max_length=1000, verbose_name='Cover Image')
    location = models.CharField(max_length=300)
    capacity = models.IntegerField()
    startDate = models.DateTimeField(verbose_name="Start Date")
    isCanceled = models.BooleanField(default=False, verbose_name="Is Canceled")
    EventType = models.TextChoices("EventType", "concert convention sport digital")
    type = models.CharField(blank=True, choices=EventType.choices, max_length=10)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

class Ticket(models.Model):
    isPremium = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tEvent = models.ForeignKey(TEvent, on_delete=models.CASCADE)


class Comments(models.Model):
    body = models.TextField(max_length=1000, verbose_name="Make a Comment")
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    eventId = models.IntegerField()

tower/tEvents/forms.py
from django import forms
from . import models

class CreateTEvent(forms.ModelForm):
    class Meta:
        model = models.TEvent
        fields = ['name', 'description', 'coverImg', 'location', 'capacity', 'startDate', 'type']
        widgets = {
            "startDate": forms.DateTimeInput(attrs={'type': 'datetime-local', 'class':'form-control mt-2'}),
            "name": forms.TextInput(attrs={'class': 'form-control mt-2'}),
            "description": forms.Textarea(attrs={'class': 'form-control mt-2'}),
            "coverImg": forms.TextInput(attrs={'class': 'form-control mt-2'}),
            "location": forms.TextInput(attrs={'class': 'form-control mt-2'}),
            "capacity": forms.NumberInput(attrs={'class': 'form-control mt-2'}),
            "type": forms.Select(attrs={'class': 'form-select mt-2'})
        }

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ['body']
        widgets= {
            "body": forms.Textarea(attrs={'class': 'form-control mt-2', 'rows':3})
        }

tower/tEvents/views.py
from django.shortcuts import render, redirect
from .models import TEvent, Ticket, Comments
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def tEventsList(request, type=None):
    if type:
        tEvents = TEvent.objects.filter(type=type)
    else:
        tEvents = TEvent.objects.all()
    return render(request, 'tEventsList.html', {'tEvents': tEvents})

def tEventDetails(request, id):
    tEvent = TEvent.objects.get(id=id)
    attendees = Ticket.objects.filter(tEvent=tEvent)
    comments = Comments.objects.filter(eventId=id)
    if attendees.filter(user=request.user):
        isAttending = True
    else:
        isAttending = False
    form = forms.CreateComment()
    return render(request, 'tEventDetails.html', {'tEvent': tEvent, 'attendees':attendees, 'isAttending': isAttending, 'form': form, 'comments':comments})

@login_required(login_url="users/login")
def cancelEvent(request, id):
    tEvent = TEvent.objects.get(id=id)
    if request.user.id == tEvent.creator.id:
        tEvent.isCanceled = True
        tEvent.save()
    return redirect('tEvents:tEventDetails', id=tEvent.id)

@login_required(login_url="users/login")
def attendEvent(request, id):
    tEvent = TEvent.objects.get(id=id)
    tick = Ticket.objects.filter(tEvent=tEvent, user=request.user)
    if not tick and tEvent.capacity > 0:
        newTick = Ticket(tEvent=tEvent, user=request.user)
        tEvent.capacity -=1
        tEvent.save()
        newTick.save()
    return redirect('tEvents:tEventDetails', id=tEvent.id)
@login_required(login_url="users/login")
def premiumEvent(request, id):
    tEvent = TEvent.objects.get(id=id)
    tick = Ticket.objects.filter(tEvent=tEvent, user=request.user)
    if not tick and tEvent.capacity > 0:
        newTick = Ticket(tEvent=tEvent, user=request.user, isPremium=True)
        tEvent.capacity -=1
        tEvent.save()
        newTick.save()
    return redirect('tEvents:tEventDetails', id=tEvent.id)

    

@login_required(login_url="users/login")
def createEvent(request):
    form = forms.CreateTEvent(request.POST, request.FILES)
    if form.is_valid():
        newEvent = form.save(commit=False)
        newEvent.creator = request.user
        newEvent.save()
        return redirect('tEvents:tEventDetails', id=newEvent.id)
    else:
        form = forms.CreateTEvent()
        return render(request, 'tEventForm.html', {'form': form})
    
@login_required(login_url="users/login")
def createComment(request, id):
    form = forms.CreateComment(request.POST, request.FILES)
    if form.is_valid():
        newComment = form.save(commit=False)
        newComment.creator = request.user
        newComment.eventId = id
        newComment.save()
    return redirect('tEvents:tEventDetails', id=id)

@login_required
def deleteComment(request, id, cId):
    comment = Comments.objects.get(id=cId)
    if comment.creator == request.user:
        comment.delete()
    return redirect('tEvents:tEventDetails', id=id)

tower/tEvents/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tower</title>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD' crossorigin='anonymous'>
</head>
<body>
    <nav class="bg-dark">
        <a href="/">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> |
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

tower/tEvents/templates/tEventDetails.html
{% extends "layout.html" %}

{% block content %}
<section class="row justify-content-center my-3">
    <div class="col-md-5">
        <div>
            <img class="detail-event-img" src="{{tEvent.coverImg}}" alt="tEvent.name">
        </div>
    </div>
    <div class="col-md-5">
        <div class="">
            <div class="d-flex justify-content-between">
                <div class="">
                    {% if tEvent.isCanceled %}
                    <h1 class="text-danger">CANCELED</h1>
                    {% endif %}
                    {% if tEvent.capacity < 1 and not tEvent.isCanceled %}
                    <h1 class="text-danger">At Capacity
                    </h1>
                    {% endif %}
                    <h3>{{ tEvent.name }}</h3>
                    <h5>{{ tEvent.type }}</h5>
                    <h6>{{ tEvent.location }}</h6>
                    <h6>Starts at: {{ tEvent.startDate }} {{ tEvent.startTime }}</h6>
                </div>
                <div class="text-end m-2">
                    {% if user == tEvent.creator and not tEvent.isCanceled %}
                    <a href="{% url 'tEvents:cancel' id=tEvent.id %}"
                    class="btn btn-danger" title="Cancel Event">Cancel</a>
                    {% endif %}
                </div>
            </div>
            <div>
                <p>{{ tEvent.description }}</p>
            </div>
            <div class="d-flex align-items-center justify-content-around">
                {% if not tEvent.isCanceled %}
                <h6 class="m-0">Capacity: {{ tEvent.capacity }}</h6>
                {% endif %}
                {% if user.is_authenticated and tEvent.capacity > 0 and not isAttending and not tEvent.isCanceled %}
                <a href="{% url 'tEvents:attend' id=tEvent.id %}" class="btn btn-outline-light">Buy Standard</a>
                {% endif %}
                {% if user.is_authenticated and tEvent.capacity > 0 and not isAttending and not tEvent.isCanceled %}
                <a href="{% url 'tEvents:premium' id=tEvent.id %}" class="btn btn-outline-light">Buy Premium</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-md-10 rounded">
        <h1>Attendees:</h1>
        {% if attendees and not tEvent.isCanceled %}
        <div class="border rounded p-2">
            <h5>
                {% for a in attendees %}
                {{a.user}}, 
                {% endfor %}
            </h5>
            {% endif %}
        </div>
    </div>
</section>

<section class="row justify-content-center">
    <div class="col-md-7 my-4 p-3 bg-light text-dark rounded">
        <form action="{% url 'tEvents:comment' id=tEvent.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <div class="text-end my-3">
                <button class="btn btn-success" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <div class="col-md-10">
        <h1>Comments:</h1>
    </div>
    {% for c in comments %}
    <div class="col-md-7 my-4 p-3 bg-light text-dark rounded d-flex justify-content-between">
        <div>
            <div class="d-flex align-items-center px-3">
                <h3>{{ c.creator }}</h3>
            </div>
            <div class="px-4">
                <p>{{ c.body }}</p>
            </div>
        </div>
        <div>
            {% if user == c.creator %}
            <a href="{% url 'tEvents:deleteComment' id=tEvent.id cId=c.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</section>




{% endblock  %}

tower/tEvents/templates/tEventForm.html
{% extends "layout.html" %}

{% block content %}
<section class="row justify-content-center my-3 mb-5">
    <div class="col-9 text-center">
        <h1>New Event:</h1>
    </div>
    <div class="col-5 mb-5">
        <form class="form-with-validation" action="{% url 'tEvents:newEvent' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button class="btn btn-light">Add Event</button>
        </form>
    </div>
    </section>

{% endblock  %}

tower/tEvents/templates/tEventsList.html
{% extends "layout.html" %}


{% block content %}
<section class="row">
    <div class="col-md-12 p-0">
        <img class="hero-img"
            src="https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
        alt="">
    </div>
</section>
<section class="row justify-content-center m-3 p-2 rounded">
    <div class="col-10 text-center">
        <a href="{% url 'tEvents:list' %}" class="btn btn-outline-light mx-4">All</a>
        <a href="{% url 'tEvents:list' type='convention' %}" class="btn btn-outline-light mx-4">Convention</a>
        <a href="{% url 'tEvents:list' type='concert' %}" class="btn btn-outline-light mx-4">Concert</a>
        <a href="{% url 'tEvents:list' type='sport' %}" class="btn btn-outline-light mx-4">Sport</a>
        <a href="{% url 'tEvents:list' type='digital' %}" class="btn btn-outline-light mx-4">Digital</a>
    </div>
</section>
<section class="row p-2">
    {% for t in tEvents %}
    <div class="col-md-3 w-shadow">
        <div title="Event Details" class="bg-light rounded my-2">
            <a class="" href="{% url 'tEvents:tEventDetails' id=t.id %}">
                <img class="rounded-top event-img" src="{{t.coverImg}}" alt="{{t.name}}">
                <h5 class="p-2 text-dark">{{ t.name }}</h5>
            </a>
        </div>
    </div>
    {% endfor %}
</section>

{% endblock  %}