tower/tower/urls.py
from django.contrib import admin
from django.urls import path, include
from tEvents import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tEvents.urls'))
]

tower/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.accountPage, name="account"),
    path('<int:id>', views.deleteTicket, name="deleteTicket")
]

tower/users/models.py
from django.db import models

# Create your models here.

tower/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class myAuthenticationForm(AuthenticationForm):
    class Meta:
        model=User
        fields= ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(myAuthenticationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password'].widget.attrs['class'] = 'form-control my-2'

class myUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields= ['username', 'password1','password2', 'first_name','last_name']

    def __init__(self, *args, **kwargs):
        super(myUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password1'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password2'].widget.attrs['class'] = 'form-control my-1'
        self.fields['first_name'].widget.attrs['class'] = 'form-control my-1'
        self.fields['last_name'].widget.attrs['class'] = 'form-control my-1'

tower/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from tEvents.models import Ticket, TEvent
from . import forms

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = forms.myAuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("tEvents:list")
    else:
        form = forms.myAuthenticationForm()
    return render(request, "login.html", {"form": form})

def register_view(request):
    if request.method == "POST":
        form = forms.myUserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("tEvents:list")
    else:
        form = forms.myUserCreationForm()
    return render(request, "register.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("tEvents:list")
    
def accountPage(request):
    if request.user:
        tickets = Ticket.objects.filter(user=request.user.id)
    return render(request, "accountPage.html", {"tickets":tickets})

def deleteTicket(request, id):
    ticket = Ticket.objects.get(id=id)
    tEvent = TEvent.objects.get(id=ticket.tEvent.id)
    if ticket.user == request.user:
        ticket.delete()
        tEvent.capacity +=1
        tEvent.save()
    return redirect("users:account")

tower/users/templates/accountPage.html
{% extends "layout.html" %}


{% block content %}
<div class="about text-center">
    {% if user.is_authenticated %}
    <h1 class="">Welcome {{ user}}</h1>
    {% else %}
    <h1>Welcome</h1>
    {% endif %}
</div>
<section class="row justify-content-center">
    {% if user.is_authenticated %}
        <div class="col-10 text-end my-4">
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger" aria-label="User Logout" title="User Logout">Logout</button>
            </form>
        </div>
    {% else %}
    <div class="col-10 text-center my-4">
        <a href="{% url 'users:login' %}">
            <span class="btn btn-success m-2" aria-label="User Login" title="User Login">Login</span>
        </a>
        <a href="{% url 'users:register' %}">
            <span class="btn btn-success m-3" aria-label="User Registration" title="User Registration">Sign Up</span>
        </a>
    </div>
    {% endif %}
</section>
<section class="row justify-content-center">
    {% for t in tickets %}
    <div class="col-md-7 d-flex justify-content-between m-4 rounded bg-blue p-2">
        <!-- events I have tickets to -->
        <div class="d-flex">
            <div>
                <img class="ticket rounded" src="{{t.tEvent.coverImg}}" alt="{{t.tEvent.name}}">
            </div>
            <div class="mx-3">
                <h3>{{ t.tEvent.name }}</h3>
                <h5>{{ t.tEvent.location }}</h5>
                <h5>{{ t.tEvent.startDate }}</h5>
            </div>
        </div>
        <div class="d-flex flex-column justify-content-between">
            <a href="{% url 'users:deleteTicket' id=t.id %}" title="Cancel ticket" class="btn btn-danger">Refund</a>
            {% if t.isPremium %}
            <h5 class="bg-gold rounded p-2">Premium</h5>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</section>
{% endblock  %}

tower/users/templates/login.html
    
{% extends "layout.html" %}
{% block content %}
<section class="row justify-content-center">
    <div class="col-6 m-1">
        <h1>User Login</h1>
    </div>
    <div class="col-6">
        <form class="form-control" action="/users/login/" method="post">
            {% csrf_token %}
            {{form}}
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <button class="btn btn-light btn-outline-dark m-2">Submit</button>
        </form>
    </div>
</section>
{% endblock  %}

tower/users/templates/register.html
    
{% extends "layout.html" %}

{% block content %}
<section class="row justify-content-center mb-5">
    <div class="col-8 my-2">
        <h1>Register a New User</h1>
    </div>
    <div class="col-8">
        <form class="form-control" action="/users/register/" method="post">
            {% csrf_token %}
            {{form}}
            <button class="btn btn-light btn-outline-dark my-3">Submit</button>
        </form>
    </div>
</section>
{% endblock  %}