tower/tEvents/urls.py
from django.urls import path
from . import views

app_name = 'tEvents'

urlpatterns = [
    path('', views.tEventsList, name="list"),
    path('<str:type>', views.tEventsList, name="list"),
    path('tEvents/<int:id>', views.tEventDetails, name="tEventDetails"),
    path('tEvents/<int:id>/cancel', views.cancelEvent, name="cancel"),
    path('tEvents/<int:id>/attend', views.attendEvent, name="attend"),
    path('tEvents/<int:id>/attend/premium', views.premiumEvent, name="premium"),
    path('tEvents/<int:id>/comment', views.createComment, name="comment"),
    path('tEvents/<int:id>/comment/<int:cId>', views.deleteComment, name="deleteComment"),
    path('new-tEvent/', views.createEvent, name="newEvent")
]

tower/tower/urls.py
from django.contrib import admin
from django.urls import path, include
from tEvents import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tEvents.urls'))
]

tower/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.accountPage, name="account"),
    path('<int:id>', views.deleteTicket, name="deleteTicket")
]

tower/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tower</title>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD' crossorigin='anonymous'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js'%}" defer></script>
</head>
<body class="bg-dark">
    <header>
        <nav class="d-flex align-items-center justify-content-between navbar navbar-expand-lg navbar-dark bg-dark px-3 border-bottom border-outline-light">
            <a href="{% url 'tEvents:list' %}" class=" selectable rounded fs-2 px-2 col-3 text-light"> <span class="btn rounded btn-dark fs-3">Home</span></a>
            
                <h1 class="text-light col-6 text-center">The Tower🦒</h1>
            
            <div class="col-3 text-end">
                {% if user.is_authenticated %}
                <a href="{% url 'tEvents:newEvent' %}" class="btn btn-outline-light mx-2 p-2">Make Event</a>
                {% endif %}
                <a class="btn btn-success btn-outline-light mx-2 p-2" href="{% url 'users:account' %}">Account</a>
            </div>
            
        </nav>
    </header>
        <main class="bg-dark text-light container-fluid">
            {% block content %}
            {% endblock %}
    </main>
</body>
</html>